### ISSUE TITLE
no matching #if...

### ISSUE THREAD

**Issue by vincenzocorso** [Southclaws/formatex#8]
When i use "sampctl package build" to compile with formatex, the compiler give me an error:

> ...\dependencies\formatex\formatex.inc:525 (error) no matching "#if..."

I watched the code and there is an error. **Line 459 is**:

> #define FORMAT_NO_DEFAULT_SPECIFIER_v

but it shoud be:

> #if !defined FORMAT_NO_DEFAULT_SPECIFIER_v

I tried and now there is no warning. Sorry for bad english.

**Comment by Southclaws** [comment]
#7 😡  @AGraber! 
jk, I should have tested before merging!

Roll back to a previous commit and you'll be fine. This will be resolved shortly.
